# Generated by Django 4.1.2 on 2022-10-17 19:23

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', web.models.UserManager()),
            ],
        ),
    ]
